### ISSUE TITLE
在所有请求中只要是包含category_id的，都会报错，请问一下这个要怎么解决

### ISSUE THREAD

**Issue by Aquarius-M** [poem-code/Gin-PinkApp#2]
{"error": "Error 1054: Unknown column 'category_id' in 'field list'"}

**Comment by axelulu** [comment]
我在首页增加了pink.sql，你重新导入一下数据库文件

**Comment by Aquarius-M** [comment]
> 我在首页增加了pink.sql，你重新导入一下数据库文件

好的，我去看看，感谢
